# Generated by Django 4.1.3 on 2022-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
